services:
  mongo:
    container_name: mongo
    image: bolkowicz/mongo:4.4.14-rc0-focal
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db


  spring-boot-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: your_mongodb_database_name
      SPRING_DATA_MONGODB_USERNAME: your_mongodb_username
      SPRING_DATA_MONGODB_PASSWORD: your_mongodb_password

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"